<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE HTML>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Sign Up Complete! - Get Digital</title>

<!-- Include header -->
<%@ include file="/WEB-INF/views/body/header.jsp"%>

</head>

<body>

	<!-- Include navbar -->
	<%@ include file="/WEB-INF/views/navigation/navbar.jsp"%>

	<div class="form-title"></div>

	<!-- Sign up form -->
	<div class="container">
		<!-- Container start -->
		<div class="page-header">
			<!-- Logo -->
			<div class="text-center logo">
				<a href="/" rel="logo"><img
					src="/resources/images/GetDigital.png" /></a>
			</div>
		</div>

		<div class="col-lg-1"></div>
		<div class="col-lg-10">
			<div class="jumbotron">
				<!-- jumbotron start -->
				<p>
					<br />
				</p>

				<div class="text-center">
					<h3>
						Thanks for registering, ${displayName}!
					</h3>

					<p>
						Before you can log in, you will need to verify your email address.<br />
						Instructions on how to do this have been sent to <em>${email}</em>
						for you.
					</p>

					<p>
						In addition to this, <em>you will need to input a code
							generated by an authenticator app (like Google Authenticator) in
							order to log in</em>.
					</p>

					<c:choose>
						<c:when test="${qrData != null}">
							<img id="2faQrCode"
								src="https://chart.googleapis.com/chart?chs=200x200&chld=M%%7C0&cht=qr&chl=${qrData}" />
							<p>
								Please scan the above QR code using your authenticator app of
								choice. (Or alternatively, manually input the secret key: <em>${secret2fa}</em>)
							</p>
						</c:when>
						<c:otherwise>
							<p>
								We were unable to generate a QR code for you to scan into your
								authenticator app of choice, so please input the secret key: <em>${secret2fa}</em>
								manually instead.
							</p>
						</c:otherwise>
					</c:choose>

					<a id="regbtn" href="/" class="btn btn-info">Return to home</a>
				</div>

			</div>
			<!-- Jumbotron end -->
		</div>
	</div>
	<!-- Container end -->

	<!-- End of Sign up form -->

	<!-- Include footer -->
	<%@ include file="/WEB-INF/views/body/footer.jsp"%>

	<!-- Scripts -->
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

</body>
</html>